// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SORMAnalytics.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260307122643_updated_configs_2")]
    partial class updated_configs_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("candles")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SORMAnalytics.Domain.Entities.AssetToFetch", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("Symbol")
                        .HasName("pk_assets_to_fetch");

                    b.ToTable("assets_to_fetch", "candles");

                    b.HasData(
                        new
                        {
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Symbol = "AAPL"
                        });
                });

            modelBuilder.Entity("SORMAnalytics.Domain.Entities.CalculatedPriceCandle", b =>
                {
                    b.Property<int>("CalculatedPriceCandleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("calculated_price_candle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalculatedPriceCandleId"));

                    b.Property<decimal?>("MA50")
                        .HasColumnType("numeric")
                        .HasColumnName("fifty_day_average_close");

                    b.Property<int>("PriceCandleId")
                        .HasColumnType("integer")
                        .HasColumnName("price_candle_id");

                    b.Property<decimal?>("MA200")
                        .HasColumnType("numeric")
                        .HasColumnName("two_hundred_day_average_close");

                    b.HasKey("CalculatedPriceCandleId")
                        .HasName("pk_calculated_price_candles");

                    b.HasIndex("PriceCandleId")
                        .IsUnique()
                        .HasDatabaseName("ix_calculated_price_candles_price_candle_id");

                    b.ToTable("calculated_price_candles", "candles");
                });

            modelBuilder.Entity("SORMAnalytics.Domain.Entities.PriceCandle", b =>
                {
                    b.Property<int>("PriceCandleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("price_candle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceCandleId"));

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric")
                        .HasColumnName("open");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<DateOnly>("Timestamp")
                        .HasColumnType("date")
                        .HasColumnName("timestamp");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("PriceCandleId")
                        .HasName("pk_price_candles");

                    b.HasIndex("Symbol", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("ix_price_candles_symbol_timestamp");

                    b.ToTable("price_candles", "candles");
                });

            modelBuilder.Entity("SORMAnalytics.Domain.Entities.CalculatedPriceCandle", b =>
                {
                    b.HasOne("SORMAnalytics.Domain.Entities.PriceCandle", "PriceCandle")
                        .WithOne("CalculatedPriceCandle")
                        .HasForeignKey("SORMAnalytics.Domain.Entities.CalculatedPriceCandle", "PriceCandleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calculated_price_candles_price_candles_price_candle_id");

                    b.Navigation("PriceCandle");
                });

            modelBuilder.Entity("SORMAnalytics.Domain.Entities.PriceCandle", b =>
                {
                    b.Navigation("CalculatedPriceCandle");
                });
#pragma warning restore 612, 618
        }
    }
}
